name: 'dispatch report'

on:
  workflow_dispatch:
    inputs:
      time:
        description: 'time'
        type: string
        required: true 

jobs:
  get_report:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: get report
        run: bash ./reporter.sh ${{ inputs.time }}
        env:
          LOCATION: ${{ secrets.LOCATION }}
          GITHUB_USERNAME: ${{ secrets.GITHAB_USERNAME }}
          SIGN: ${{ secrets.SIGN }}
          POCKET_CONSUMER_KEY: ${{ secrets.POCKET_CONSUMER_KEY }}
          POCKET_ACCESS_TOKEN: ${{ secrets.POCKET_ACCESS_TOKEN }}

      - name: send email
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Autor
          html_body: file://rst.html
          to: ${{ secrets.MAIL_USERNAME }}
          from: Autor
