name: 'GitHub Actions Weather Bot'
on:
  push:
  schedule:
    - cron: '39 12 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1

      - name: 'Get weather report'
        run: bash ./weather.sh
        
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Workflow finished
          body: Job completed ${{job.status}}
          to: 792112796@qq.com
          from: Me
