name: 'GitHub Actions Weather Bot'
on:
  push:
    branches:
      - main
jobs:
  get_report:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2

      - name: Get morning report
        if: github.event.schedule != '30 5 * * 1,3'
        run: bash ./reporter.sh morning
        
      - name: Send email
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Autor
          html_body: file://data/morning.html
          to: acker_autor@163.com
          from: Autor
