name: 'GitHub Actions Weather Bot'
on:
  push:
  schedule:
    - cron: '01 25 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1

      - name: 'Get weather report'
        run: bash ./weather.sh
        
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: acker2880@gmail.com
          password: BywordjssQ&!qg11
          subject: Workflow finished
          body: Job completed ${{job.status}}
          to: acker2880@gmail.com
          from: Me
